"""add soft delete columns to leads, leadFile, tasks, note

Revision ID: 1bba9e1db76c
Revises: bebd3db14561
Create Date: 2026-08-22 13:36:32.939882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bba9e1db76c'
down_revision: Union[str, Sequence[str], None] = 'bebd3db14561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_files', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('lead_files', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead_files', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('leads', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('notes', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('notes', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'deleted_by')
    op.drop_column('tasks', 'deleted_at')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'deleted_by')
    op.drop_column('notes', 'deleted_at')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'deleted_by')
    op.drop_column('leads', 'deleted_at')
    op.drop_constraint(None, 'lead_files', type_='foreignkey')
    op.drop_column('lead_files', 'deleted_by')
    op.drop_column('lead_files', 'deleted_at')
    # ### end Alembic commands ###
