"""add pipeline_stages table and lead.stage_id

Revision ID: 3ab1feb4f524
Revises: 2bc5e57d6f70
Create Date: 2026-08-15 15:56:17.801124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab1feb4f524'
down_revision: Union[str, Sequence[str], None] = '2bc5e57d6f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_company_id'), 'pipeline_stages', ['company_id'], unique=False)
    op.add_column('leads', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'pipeline_stages', ['stage_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'stage_id')
    op.drop_index(op.f('ix_pipeline_stages_company_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    # ### end Alembic commands ###
