"""add note threading and mentions

Revision ID: 513bb87f5b11
Revises: bd8e22b6449f
Create Date: 2026-08-19 09:31:11.489747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513bb87f5b11'
down_revision: Union[str, Sequence[str], None] = 'bd8e22b6449f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_mentions_mentioned_user_id'), 'note_mentions', ['mentioned_user_id'], unique=False)
    op.create_index(op.f('ix_note_mentions_note_id'), 'note_mentions', ['note_id'], unique=False)
    op.add_column('notes', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'notes', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'parent_id')
    op.drop_index(op.f('ix_note_mentions_note_id'), table_name='note_mentions')
    op.drop_index(op.f('ix_note_mentions_mentioned_user_id'), table_name='note_mentions')
    op.drop_table('note_mentions')
    # ### end Alembic commands ###
