"""add companies table and comapines_id fk

Revision ID: b9c9b8c6f3ad
Revises: ba712120abb7
Create Date: 2026-08-05 14:11:42.661613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c9b8c6f3ad'
down_revision: Union[str, Sequence[str], None] = 'ba712120abb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('leads', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
